# -*- coding: utf-8 -*-
# Tradução dos nomes de presentes do TikTok Live para português

GIFTS_PT = {
    "rose": "Rosa",
    "teddy bear": "Ursinho de Pelúcia",
    "concert": "Concerto",
    "panda": "Panda",
    "sun cream": "Protetor Solar",
    "love bang": "Explosão de Amor",
    "rainbow puke": "Vômito Arco-Íris",
    "lion": "Leão",
    "robot": "Robô",
    "crown": "Coroa",
    "little crown": "Pequena Coroa",
    "capybara": "Capivara",
    "mishka bear": "Urso Mishka",
    "paper crane": "Grou de Papel",
    "birthday cake": "Bolo de Aniversário",
    "ice cream": "Sorvete",
    "basketball": "Basquete",
    "fireworks": "Fogos de Artifício",
    "diamond": "Diamante",
    "super fan": "Super Fã",
    "grand gift": "Presente Especial",
    "magic wand": "Varinha Mágica",
    "champagne": "Champanhe",
    "guitar": "Guitarra",
    "piano": "Piano",
    "flower": "Flor",
    "star": "Estrela",
    "heart": "Coração",
    "perfume": "Perfume",
    "confetti": "Confete",
    "sunglasses": "Óculos de Sol",
    "money rain": "Chuva de Dinheiro",
    "disco ball": "Bola de Disco",
    "mermaid": "Sereia",
    "airplane": "Avião",
    "planet": "Planeta",
    "diamond flight": "Voo de Diamante",
    "tiktok universe": "Universo TikTok",
    "gold medal": "Medalha de Ouro",
}
